### PR TITLE
Make docster a wee-bit smarter

### PR DESCRIPTION
**Pull request by locks**
This is helpful for FAQs. I've made it so only voice/half-op/ops can use the learn/forget commands.
I've also seeded learnings.json with an example of a useful resource.

### CODE REVIEW

**Comment by danmcclain** [comment]
This is up on Heroku, so the file system is ephemeral. We'd want to store these values in something like redis, otherwise docster would be quick to forget :scream:

**Comment by locks** [comment]
aw, poop :C that's a really big dependency for something so simple.

**Comment by danmcclain** [comment]
I can update this to use redis, shouldn't be a big issue

**Comment by locks** [comment]
:+1: thank you. Let me know when you deploy it so I can ask the admins for +v.

**Comment by danmcclain** [comment]
Merging this as is for now, will update to redis soon. Thanks again

**Comment by danmcclain** [comment]
Deployed this, and made the things it learns specific to the channel

**Pull request merged**
